/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.smict.struts.form.Booking1Form;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2015
 * 
 * XDoclet definition:
 * @struts.action path="/booking2Start" name="booking1Form" scope="request" validate="true"
 * @struts.action-forward name="room_not_empty" path="/room_not_empty.jsp"
 * @struts.action-forward name="success" path="/booking2.jsp"
 */
public class Booking2StartAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Booking1Form booking1Form = (Booking1Form) form;// TODO Auto-generated method stub
		return null;
	}
}