/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-26-2015
 * 
 * XDoclet definition:
 * @struts.form name="booking3Form"
 */
public class Booking3Form extends ActionForm {
	/*
	 * Generated fields
	 */

	/** special_request property */
	private String special_request;

	/** oc_title property */
	private String oc_title;

	/** title property */
	private String title;

	/** intercode property */
	private String intercode;

	/** email property */
	private String email;

	/** oc_name_sure property */
	private String oc_name_sure;
	
	//for loop occupancy
	private String oc_title1,oc_title2,oc_title3,oc_title4,oc_title5,oc_title6,oc_title7,oc_title8,oc_title9,oc_title10;
	private String oc_name_sure1,oc_name_sure2,oc_name_sure3,oc_name_sure4,oc_name_sure5,oc_name_sure6,oc_name_sure7,oc_name_sure8,oc_name_sure9,oc_name_sure10;
	/** phonenum property */
	private String phonenum;

	/** country property */
	private String country;

	/** name_sure property */
	private String name_sure;
	private String room_id;
	//for finish booking
	//from booking2
	private String roomtype_name,roomtype_picpath,roomtype_id,dial_code,true_calling;
	//private String;
	/*
	 * Generated Methods
	 */

	public Booking3Form (){};
	public Booking3Form(String usefor, String s1) {
		// TODO Auto-generated constructor stub
		if (usefor == "show_countries"){
			this.country = s1;
		}else{
			this.dial_code = s1;
		}
	}

	public Booking3Form(String usefor, String s1, String s2) {
		// TODO Auto-generated constructor stub
		if(usefor == "numcode"){
			this.dial_code = s1;
			this.true_calling = s2;
		}
	}
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the special_request.
	 * @return String
	 */
	public String getSpecial_request() {
		return special_request;
	}

	/** 
	 * Set the special_request.
	 * @param special_request The special_request to set
	 */
	public void setSpecial_request(String special_request) {
		this.special_request = special_request;
	}

	/** 
	 * Returns the oc_title.
	 * @return String
	 */
	public String getOc_title() {
		return oc_title;
	}

	/** 
	 * Set the oc_title.
	 * @param oc_title The oc_title to set
	 */
	public void setOc_title(String oc_title) {
		this.oc_title = oc_title;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the intercode.
	 * @return String
	 */
	public String getIntercode() {
		return intercode;
	}

	/** 
	 * Set the intercode.
	 * @param intercode The intercode to set
	 */
	public void setIntercode(String intercode) {
		this.intercode = intercode;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the oc_name_sure.
	 * @return String
	 */
	public String getOc_name_sure() {
		return oc_name_sure;
	}

	/** 
	 * Set the oc_name_sure.
	 * @param oc_name_sure The oc_name_sure to set
	 */
	public void setOc_name_sure(String oc_name_sure) {
		this.oc_name_sure = oc_name_sure;
	}

	/** 
	 * Returns the phonenum.
	 * @return String
	 */
	public String getPhonenum() {
		return phonenum;
	}

	/** 
	 * Set the phonenum.
	 * @param phonenum The phonenum to set
	 */
	public void setPhonenum(String phonenum) {
		this.phonenum = phonenum;
	}

	/** 
	 * Returns the country.
	 * @return String
	 */
	public String getCountry() {
		return country;
	}

	/** 
	 * Set the country.
	 * @param country The country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/** 
	 * Returns the name_sure.
	 * @return String
	 */
	public String getName_sure() {
		return name_sure;
	}

	/** 
	 * Set the name_sure.
	 * @param name_sure The name_sure to set
	 */
	public void setName_sure(String name_sure) {
		this.name_sure = name_sure;
	}
	public String getRoom_id() {
		return room_id;
	}
	public void setRoom_id(String roomId) {
		room_id = roomId;
	}
	public String getRoomtype_name() {
		return roomtype_name;
	}
	public void setRoomtype_name(String roomtypeName) {
		roomtype_name = roomtypeName;
	}
	public String getRoomtype_picpath() {
		return roomtype_picpath;
	}
	public void setRoomtype_picpath(String roomtypePicpath) {
		roomtype_picpath = roomtypePicpath;
	}
	public String getRoomtype_id() {
		return roomtype_id;
	}
	public void setRoomtype_id(String roomtypeId) {
		roomtype_id = roomtypeId;
	}
	public String getDial_code() {
		return dial_code;
	}
	public void setDial_code(String dialCode) {
		dial_code = dialCode;
	}
	public String getTrue_calling() {
		return true_calling;
	}
	public void setTrue_calling(String trueCalling) {
		true_calling = trueCalling;
	}
	public String getOc_title1() {
		return oc_title1;
	}
	public void setOc_title1(String ocTitle1) {
		oc_title1 = ocTitle1;
	}
	public String getOc_title2() {
		return oc_title2;
	}
	public void setOc_title2(String ocTitle2) {
		oc_title2 = ocTitle2;
	}
	public String getOc_title3() {
		return oc_title3;
	}
	public void setOc_title3(String ocTitle3) {
		oc_title3 = ocTitle3;
	}
	public String getOc_title4() {
		return oc_title4;
	}
	public void setOc_title4(String ocTitle4) {
		oc_title4 = ocTitle4;
	}
	public String getOc_title5() {
		return oc_title5;
	}
	public void setOc_title5(String ocTitle5) {
		oc_title5 = ocTitle5;
	}
	public String getOc_title6() {
		return oc_title6;
	}
	public void setOc_title6(String ocTitle6) {
		oc_title6 = ocTitle6;
	}
	public String getOc_title7() {
		return oc_title7;
	}
	public void setOc_title7(String ocTitle7) {
		oc_title7 = ocTitle7;
	}
	public String getOc_title8() {
		return oc_title8;
	}
	public void setOc_title8(String ocTitle8) {
		oc_title8 = ocTitle8;
	}
	public String getOc_title9() {
		return oc_title9;
	}
	public void setOc_title9(String ocTitle9) {
		oc_title9 = ocTitle9;
	}
	public String getOc_title10() {
		return oc_title10;
	}
	public void setOc_title10(String ocTitle10) {
		oc_title10 = ocTitle10;
	}
	public String getOc_name_sure1() {
		return oc_name_sure1;
	}
	public void setOc_name_sure1(String ocNameSure1) {
		oc_name_sure1 = ocNameSure1;
	}
	public String getOc_name_sure2() {
		return oc_name_sure2;
	}
	public void setOc_name_sure2(String ocNameSure2) {
		oc_name_sure2 = ocNameSure2;
	}
	public String getOc_name_sure3() {
		return oc_name_sure3;
	}
	public void setOc_name_sure3(String ocNameSure3) {
		oc_name_sure3 = ocNameSure3;
	}
	public String getOc_name_sure4() {
		return oc_name_sure4;
	}
	public void setOc_name_sure4(String ocNameSure4) {
		oc_name_sure4 = ocNameSure4;
	}
	public String getOc_name_sure5() {
		return oc_name_sure5;
	}
	public void setOc_name_sure5(String ocNameSure5) {
		oc_name_sure5 = ocNameSure5;
	}
	public String getOc_name_sure6() {
		return oc_name_sure6;
	}
	public void setOc_name_sure6(String ocNameSure6) {
		oc_name_sure6 = ocNameSure6;
	}
	public String getOc_name_sure7() {
		return oc_name_sure7;
	}
	public void setOc_name_sure7(String ocNameSure7) {
		oc_name_sure7 = ocNameSure7;
	}
	public String getOc_name_sure8() {
		return oc_name_sure8;
	}
	public void setOc_name_sure8(String ocNameSure8) {
		oc_name_sure8 = ocNameSure8;
	}
	public String getOc_name_sure9() {
		return oc_name_sure9;
	}
	public void setOc_name_sure9(String ocNameSure9) {
		oc_name_sure9 = ocNameSure9;
	}
	public String getOc_name_sure10() {
		return oc_name_sure10;
	}
	public void setOc_name_sure10(String ocNameSure10) {
		oc_name_sure10 = ocNameSure10;
	}
}