/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2015
 * 
 * XDoclet definition:
 * @struts.form name="booking2Form"
 */
public class Booking2Form extends ActionForm {
	/*
	 * Generated Methods
	 */
	//------------------------------------------------for show
	private String room_id,roomtype_id,roomtype_name,roomtype_desc,roomtype_detail,roomtype_single_bed,roomtype_double_bed,roomtype_guest,roomtype_price,pic_status,roomtype_picpath;

	//------------------------------------------------for input
	private String submit ;
	//Constructor
	public Booking2Form() {};
	
	public Booking2Form(String s1, String s2, String s3,
			String s4, String s5, String d1,
			String i1, String i2, String i3,String i4,String i5) {
		// TODO Auto-generated constructor stub
		this.room_id= s1;
		this.roomtype_id = s2;
		this.roomtype_name = s3;
		this.roomtype_desc = s4;
		this.roomtype_detail = s5;
		this.roomtype_single_bed = i1;
		this.roomtype_double_bed = i2;
		this.roomtype_guest = i3;
		this.roomtype_price = d1;
		this.pic_status = i4;
		this.roomtype_picpath = i5;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getRoom_id() {
		return room_id;
	}

	public void setRoom_id(String roomId) {
		room_id = roomId;
	}

	public String getRoomtype_id() {
		return roomtype_id;
	}

	public void setRoomtype_id(String roomtypeId) {
		roomtype_id = roomtypeId;
	}

	public String getRoomtype_name() {
		return roomtype_name;
	}

	public void setRoomtype_name(String roomtypeName) {
		roomtype_name = roomtypeName;
	}

	public String getRoomtype_desc() {
		return roomtype_desc;
	}

	public void setRoomtype_desc(String roomtypeDesc) {
		roomtype_desc = roomtypeDesc;
	}

	public String getRoomtype_detail() {
		return roomtype_detail;
	}

	public void setRoomtype_detail(String roomtypeDetail) {
		roomtype_detail = roomtypeDetail;
	}

	public String getRoomtype_single_bed() {
		return roomtype_single_bed;
	}

	public void setRoomtype_single_bed(String roomtypeSingleBed) {
		roomtype_single_bed = roomtypeSingleBed;
	}

	public String getRoomtype_double_bed() {
		return roomtype_double_bed;
	}

	public void setRoomtype_double_bed(String roomtypeDoubleBed) {
		roomtype_double_bed = roomtypeDoubleBed;
	}

	public String getRoomtype_guest() {
		return roomtype_guest;
	}

	public void setRoomtype_guest(String roomtypeGuest) {
		roomtype_guest = roomtypeGuest;
	}

	public String getRoomtype_price() {
		return roomtype_price;
	}

	public void setRoomtype_price(String roomtypePrice) {
		roomtype_price = roomtypePrice;
	}

	public String getSubmit() {
		return submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}

	public String getPic_status() {
		return pic_status;
	}

	public void setPic_status(String picStatus) {
		pic_status = picStatus;
	}

	public String getRoomtype_picpath() {
		return roomtype_picpath;
	}

	public void setRoomtype_picpath(String roomtypePicpath) {
		roomtype_picpath = roomtypePicpath;
	}
}